name: "Publish demo & benchmark pages to GitHub Pages"

permissions:
  packages: write
  contents: write

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: https://npm.pkg.github.com/
          scope: "@sportvot"
      - run: npm ci
      - name: Configure Git for pushing commits
        # Embed the access token directly into the remote URL so that the gh-pages library can pick it up
        run: git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - run: npm run deploy -- -u 'github-actions-bot <support+actions@github.com>'
      - name: Add User
        run: npm add-user
      - name: Publish package
        run: npm run publish-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
